name: iOS Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - '16'
        destination:
          - 'platform=iOS Simulator,OS=18.1,name=iPhone 16'
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Checkout repository
        uses: actions/checkout@v6
           
      - name: Create Secrets.xcconfig
        run: echo "${{ secrets.SECRETS_XCCONFIG }}" > $GITHUB_WORKSPACE/Secrets.xcconfig
        
      - name: Create Sentry upload Debug Symbols script
        run: echo "${{ secrets.SENTRY_UPLOAD_DEBUG_SYMBOLS_SCRIPT }}" > $GITHUB_WORKSPACE/scripts/sentry-upload-dsym.sh

      - name: Create GoogleService-Info
        run: echo "${{ secrets.GOOGLE_SERVICES_INFO }}" > $GITHUB_WORKSPACE/Tanga/GoogleService-Info.plist

      - name: Build
        run: |
          xcodebuild clean build \
          -project Tanga.xcodeproj \
          -scheme Tanga \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator'

